image: scrapinghub

script:
  - git restore-mtime
  - pip install -U tox coverage shub
  - tox

notify:
  slack:
    webhook_url: $SLACK_HOOK_URL
    username: 'drone'
    on_started: false
    on_success: false
    on_failure: true
