image: scrapinghub

script:
  - git restore-mtime
  - pip install -U tox coverage shub
  - tox

notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#dataservices'
    on_started: false
    on_success: false
    on_failure: true
